import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { SpeedInsights } from '@vercel/speed-insights/next'

import Footer from '@/components/Layout/Footer'
import MainHeader from '@/components/Layout/MainHeader'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='vi'>
      <head>
        <title>SportSpace</title>
      </head>
      <body className={`${inter.className} font-Inter`}>
        <MainHeader />
        {children}
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  )
}
