import type { Metadata } from 'next'

import { SpeedInsights } from '@vercel/speed-insights/next'

import { QueryProvider } from '@/providers/queryProvider'

import './globals.css'

export const metadata: Metadata = {
  title: 'SportSpace',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='vi'>
      <head>
        <title>SportSpace</title>
      </head>
      <body className={`relative font-Inter`}>
        <QueryProvider>
          <main>{children}</main>
          <SpeedInsights />
        </QueryProvider>
      </body>
    </html>
  )
}
